//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON
    {
        public string HoaDonID { get; set; }
        public string monanID { get; set; }
        public Nullable<int> Dongia { get; set; }
    
        public virtual MONAN MONAN { get; set; }
    }
}
