//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string HoaDonID { get; set; }
        public string NhanVienID { get; set; }
        public Nullable<int> Giamgia { get; set; }
        public string BanID { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> Tongtien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
