//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_Án_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonXuat
    {
        public string HoaDonXuatID { get; set; }
        public string NhanVien_Xuat { get; set; }
        public string NhanVien_Nhan { get; set; }
        public string KhoID { get; set; }
        public Nullable<System.DateTime> Ngayxuat { get; set; }
        public Nullable<System.DateTime> Ngaynhan { get; set; }
    
        public virtual CHITIET_HDX CHITIET_HDX { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
